In [1]:
#Import needed libraries
import pandas as pd
import numpy as np

In [2]:
#Import the data frame
artic = pd.read_csv("data/Arctic Species Trend Index (ASTI) _Marine.csv")

In [3]:
#Import my cleaning functions
import sys
sys.path.append("../")
from src.cleaning_magic import *

In [4]:
print("Before cleaning artic has ", artic.shape[1], "columns and ", artic.shape[0], "rows.")

Before cleaning artic has  236 columns and  23499 rows.


Before cleaning artic has  236 columns and  23499 rows.

In [5]:
df_firstclean(artic)

id                scientificName  \
0      00009783-7692-461f-8e4f-bac887cbaae8            Fulmarus glacialis   
1      0001efe0-9d60-4004-8a98-d0111462e8f6         Hemilepidotus jordani   
2      00032867-c147-4c6a-8fb0-267aecd2dbae       Glyptocephalus zachirus   
3      00033525-9743-4be9-88dd-ac34b84b62c5                  Gadus morhua   
4      00039387-69f2-4c57-b8ff-702ae303c253                    Uria aalge   
...                                     ...                           ...   
23494  fffa0be8-5d7e-4fbf-b601-c9737efb0096          Pluvialis squatarola   
23495  fffa4829-8ac5-486d-a778-2e68d2539619             Larus glaucescens   
23496  fffc584c-0d69-4033-9185-e75b7792db4a     Histrionicus histrionicus   
23497  fffedbdf-63ab-4686-9839-9ea5ed7653f1  Reinhardtius hippoglossoides   
23498  ffff3cfb-eb4a-4621-b23a-4b2a5aa5c0f5                Morus bassanus   

      scientificNameAuthorship  decimalLongitude  decimalLatitude  \
0             (Linnaeus, 1761)        -169.55806         56.57222   
1                   Bean, 1881        -176.00000         52.00000   
2             Lockington, 1879        -170.99778         58.13722   
3               Linnaeus, 1758          15.33222         71.50722   
4          (Pontoppidan, 1763)        -162.03333         58.65000   
...                        ...               ...              ...   
23494         (Linnaeus, 1758)         106.30000         72.40000   
23495            Naumann, 1840        -155.60000         57.75000   
23496         (Linnaeus, 1758)         166.27306         55.00083   
23497          (Walbaum, 1792)        -162.00000         57.68333   
23498         (Linnaeus, 1758)         -20.31667         63.41667   

                                scientificNameID  absence  aphiaID  \
0      urn:lsid:marinespecies.org:taxname:137195    False   137195   
1      urn:lsid:marinespecies.org:taxname:254522    False   254522   
2      urn:lsid:marinespecies.org:taxname:274287    False   274287   
3      urn:lsid:marinespecies.org:taxname:126436    False   126436   
4      urn:lsid:marinespecies.org:taxname:137133    False   137133   
...                                          ...      ...      ...   
23494  urn:lsid:marinespecies.org:taxname:159137    False   159137   
23495  urn:lsid:marinespecies.org:taxname:343911    False   343911   
23496  urn:lsid:marinespecies.org:taxname:159092    False   159092   
23497  urn:lsid:marinespecies.org:taxname:127144    False   127144   
23498  urn:lsid:marinespecies.org:taxname:148776    False   148776   

          basisOfRecord brackish  ...                       species speciesid  \
0      HumanObservation      NaN  ...            Fulmarus glacialis  137195.0   
1      HumanObservation    False  ...         Hemilepidotus jordani  254522.0   
2      HumanObservation    False  ...       Glyptocephalus zachirus  274287.0   
3      HumanObservation     True  ...                  Gadus morhua  126436.0   
4      HumanObservation      NaN  ...                    Uria aalge  137133.0   
...                 ...      ...  ...                           ...       ...   
23494  HumanObservation      NaN  ...          Pluvialis squatarola  159137.0   
23495  HumanObservation      NaN  ...             Larus glaucescens  343911.0   
23496  HumanObservation      NaN  ...     Histrionicus histrionicus  159092.0   
23497  HumanObservation    False  ...  Reinhardtius hippoglossoides  127144.0   
23498  HumanObservation      NaN  ...                Morus bassanus  148776.0   

        subphylum subphylumid superclass superclassid terrestrial  \
0      Vertebrata      146419  Tetrapoda         1831         NaN   
1      Vertebrata      146419     Pisces        11676       False   
2      Vertebrata      146419     Pisces        11676       False   
3      Vertebrata      146419     Pisces        11676       False   
4      Vertebrata      146419  Tetrapoda         1831         NaN   
...           ...         ...        ...          ...      

Since there are too many species to investigate (114) all of them at the same time,
we are going to focus only on marine mammals.
<br>
For this we will create a new dataset that reflects only these records

In [7]:
artic_mammals = columnvalue_filter (artic,'class', 'Mammalia')

In [8]:
artic_mammals

id         scientificName  \
5      0004591d-84bd-47ae-b145-fc67d721f8b0        Ursus maritimus   
7      0019a345-47d1-41a5-969c-bcce0ddfa5f9      Odobenus rosmarus   
12     0027d548-c43a-455b-b1e5-87ba78253271  Eschrichtius robustus   
13     002b122c-610c-440a-9d95-140762f27127         Enhydra lutris   
23     004e63dd-cafa-4688-a1c0-0f66ea853b91         Enhydra lutris   
...                                     ...                    ...   
23458  ffa65686-6402-4f75-9884-7284d03afd8f     Balaena mysticetus   
23459  ffa7689b-f4dd-402f-b6de-ccb0dfaa7d81      Monodon monoceros   
23461  ffac9b15-064c-489d-81a8-40e3757022b7     Eumetopias jubatus   
23462  ffae907b-0344-4182-9854-244f6845cb8e        Ursus maritimus   
23472  ffc85712-aed6-41d8-a60e-4063379ee3de  Delphinapterus leucas   

      scientificNameAuthorship  decimalLongitude  decimalLatitude  \
5                 Phipps, 1774         -83.63750         56.42278   
7                Illiger, 1815        -172.61000         53.58111   
12            Lilljeborg, 1861        -170.46667         64.00000   
13              Linnaeus, 1758        -178.96306         51.38694   
23              Linnaeus, 1758        -162.01667         54.86667   
...                        ...               ...              ...   
23458           Linnaeus, 1758        -168.74028         63.70389   
23459           Linnaeus, 1758         -88.00000         60.00000   
23461         (Schreber, 1776)        -152.31472         56.16583   
23462             Phipps, 1774        -150.00028         64.00028   
23472             Pallas, 1776         -82.00000         60.00000   

                                scientificNameID  absence  aphiaID  \
5      urn:lsid:marinespecies.org:taxname:137085    False   137085   
7      urn:lsid:marinespecies.org:taxname:137077    False   137077   
12     urn:lsid:marinespecies.org:taxname:137112    False   137112   
13     urn:lsid:marinespecies.org:taxname:242598    False   242598   
23     urn:lsid:marinespecies.org:taxname:242598    False   242598   
...                                          ...      ...      ...   
23458  urn:lsid:marinespecies.org:taxname:137086    False   137086   
23459  urn:lsid:marinespecies.org:taxname:137116    False   137116   
23461  urn:lsid:marinespecies.org:taxname:254999    False   254999   
23462  urn:lsid:marinespecies.org:taxname:137085    False   137085   
23472  urn:lsid:marinespecies.org:taxname:137115    False   137115   

          basisOfRecord brackish  ...                species speciesid  \
5      HumanObservation      NaN  ...        Ursus maritimus  137085.0   
7      HumanObservation      NaN  ...      Odobenus rosmarus  137077.0   
12     HumanObservation      NaN  ...  Eschrichtius robustus  137112.0   
13     HumanObservation      NaN  ...         Enhydra lutris  242598.0   
23     HumanObservation      NaN  ...         Enhydra lutris  242598.0   
...                 ...      ...  ...                    ...       ...   
23458  HumanObservation      NaN  ...     Balaena mysticetus  137086.0   
23459  HumanObservation      NaN  ...      Monodon monoceros  137116.0   
23461  HumanObservation      NaN  ...     Eumetopias jubatus  254999.0   
23462  HumanObservation      NaN  ...        Ursus maritimus  137085.0   
23472  HumanObservation     True  ...  Delphinapterus leucas  137115.0   

        subphylum subphylumid superclass superclassid terrestrial  \
5      Vertebrata      146419  Tetrapoda         1831         NaN   
7      Vertebrata      146419  Tetrapoda         1831         NaN   
12     Vertebrata      146419  Tetrapoda         1831         NaN   
13     Vertebrata      146419  Tetrapoda         1831         NaN   
23     Vertebrata      146419  Tetrapoda         1831         NaN   
...           ...         ...        ...          ...         ...   
23458  Vertebrata      146419  Tetrapoda         1831         NaN   
23459  Vertebrata      146419  Tetrapoda         1831         NaN   
23461  Vertebrata   

In [14]:
artic_mammals.to_csv("data/artic_mammals_obis.csv")